# -*- coding: utf-8 -*-
"""auto_label.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWTkv6k_QhOnWbkjLuhHiJVLuoJ5d0aF
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers torch pillow -q

import os
import csv
import re
from transformers import TrOCRProcessor, VisionEncoderDecoderModel
from PIL import Image

def generate_labels(image_folder, out_csv):
    print("Loading TrOCR large model...")
    processor = TrOCRProcessor.from_pretrained('microsoft/trocr-large-handwritten')
    model = VisionEncoderDecoderModel.from_pretrained('microsoft/trocr-large-handwritten')
    print("Model loaded!")

    # --- Step 1: Load already processed filenames ---
    done = set()
    if os.path.exists(out_csv):
        with open(out_csv, 'r', encoding='utf-8') as f:
            reader = csv.reader(f)
            next(reader, None)  # skip header safely
            for row in reader:
                if row:
                    done.add(row[0])

    print(f"Already processed: {len(done)} files")

    # --- Step 2: Prepare CSV (append mode) ---
    file_exists = os.path.exists(out_csv)
    with open(out_csv, "a", newline='', encoding='utf-8') as f:
        writer = csv.writer(f)

        # write header only if file is new
        if not file_exists:
            writer.writerow(['Filename', 'Extracted_text'])

        # --- Step 3: Sort images numerically ---
        images = sorted(
            [f for f in os.listdir(image_folder) if f.endswith('.jpeg')],
            key=lambda x: [int(n) for n in re.findall(r'\d+', x)]
        )

        total = len(images)
        print(f"Total images: {total}")

        # --- Step 4: Process images ---
        for i, filename in enumerate(images):

            # skip already processed
            if filename in done:
                print(f"[SKIP] {filename}")
                continue

            try:
                img_path = os.path.join(image_folder, filename)
                image = Image.open(img_path).convert('RGB')

                pixel_values = processor(images=image, return_tensors='pt').pixel_values
                generated_ids = model.generate(pixel_values, max_new_tokens=50)
                text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

                writer.writerow([filename, text])
                f.flush()

                print(f"[{i+1}/{total}] {filename} → {text}")

            except Exception as e:
                print(f"[ERROR] {filename}: {e}")

# Paths
image_folder = '/content/drive/MyDrive/Examlens/final_croped'
output_csv = '/content/drive/MyDrive/Examlens/labels.csv'

os.makedirs('/content/drive/MyDrive/Examlens', exist_ok=True)

generate_labels(image_folder, output_csv)
print("CSV ready!")

